account_id = "6ca3fa16f4f94a6d565cdf361cab3b48"
name = "my-site"
type = "javascript"
workers_dev = true
site = { bucket = "./public" }
target_type = "js"
route = ""
zone_id = ""

[build]
command = "npm run build"
[build.upload]
format = "modules"
main = "./index.mjs"